numb_threads: 32
max_memory: 8
output_dir: '/path/output_directory'
reference:
  alias: 'mga'
  mtf: 'AY497292'
  mtm: 'AY363687'
samples:
  sample_01:
    alias: 'LOLA_Gill'
    accession: 'ERR4296979'
  sample_02:
    alias: 'LOLA_Digestive'
    accession: 'ERR4296980'
other_spp:
  specie_01:
    alias: 'rph'
    mtf: 'MT757748'
    mtm: 'MT757749'
  specie_02:
    alias: 'mtr'
    mtf: 'GU936625'
    mtm: 'HM462081'
  specie_03:
    alias: 'mca'
    mtf: 'JX486124'
    mtm: 'JX486123'
  specie_04:
    alias: 'mse'
    mtf: 'GU001953'
    mtm: 'GU001954'
  specie_05:
    alias: 'med'
    mtf: 'MF407676'
    mtm: 'HM489874'
  specie_06:
    alias: 'cgi'
    mt: 'MZ497416'